config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :crimes, except: :new do
    get 'crime_json' => 'crimes#crime_json'
    resources :chatrooms, except: [:index, :update, :edit] do
      resources :messages, only: :create
    end

    # crimes/:id/chatrooms/:id
    #for the chatroom, it needs: new, create, show, delete

    # crime_chatroom GET    /crimes/:crime_id/chatrooms/:id(.:format)       chatrooms#show
    # crime_teams POST   /crimes/:crime_id/teams(.:format) teams#create

    resources :teams, only: [:create, :update, :destroy]  #before it was resources :teams, only [:create, :index]
  end
  #added the line above to create a custom route for team index

  resources :skillsets, only: [:new, :create, :edit, :update]

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end

  get 'profile', to: 'pages#profile'
  get 'current_user_json' => 'pages#current_user_json'
end

app/views/pages/_edit_description.html.erb
<div class="description-edit-form" style="display:none">
  <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :patch }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :description, as: :text %>
  <%= f.input :current_password,
              hint: "we need your current password to confirm your changes",
              required: true,
              input_html: { autocomplete: "current-password" } %>
  <%= f.button :submit, 'Save' %>
  <% end %>
</div>

app/views/pages/_form.html.erb
<div class="crime-form-container">

  <div id="crime-form-1" style="display:show;">
    <%= simple_form_for @crime do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
    <div class="nav-btn-container">
      <%= link_to 'Back', profile_path, class: 'nav-text' %>
      <a href="#" class="crime-form-btn nav-text">Next</a>
    </div>
  </div>

  

  <div id="crime-form-2" style="display:none;">
      <%= f.input :date %>
      <%= f.input :reward %>
      <%= f.input :photo, as: :file %>
      <span>Do you agree with the <a href="#"><small>terms of service</small></a>?</span>
      <%= f.button :submit, 'I agree', class: 'nav-text very-light-ruby', id: 'agree-link' %></small>
      <% end %>
      <div class="nav-btn-container">
        <a href="#" class="crime-form-btn nav-text">Back</a>
        <a href="#" class="skillset-form-btn nav-text">Next</a>
      </div>
  </div>

  <div id="crime-form-skillset" style="display:none;">
      <p>Define the necessary skills for your crime.</p>
      <%= simple_form_for @skillset do |f| %>
      <%= f.input :close_combat, as: :range %>
      <%= f.input :long_range_weapons, as: :range %>
      <%= f.input :mid_range_weapons, as: :range %>
      <%= f.input :explosives, as: :range %>
      <%= f.input :infiltration, as: :range %>
      <%= f.input :hacking, as: :range %>
      <%= f.input :lockpicking, as: :range %>
      <%= f.input :seduction, as: :range %>
      <div class="nav-btn-container">
        <a href="#" class="skillset-form-btn nav-text">Back</a>
        <%= f.button :submit, 'Create Crime', class: 'nav-test submit-crime-skillset', id: 'create-crime' %>
        <% end %>
      </div>
  </div>

</div>

app/views/pages/_skillset-form.html.erb
<p class="form-title">Define your set of skills.</p>
<p><small>This will help to find the best job matches for you.</small></p>
<%= simple_form_for @skillset do |f| %>
  <%= f.input :close_combat, as: :range %>
  <%= f.input :long_range_weapons, as: :range %>
  <%= f.input :mid_range_weapons, as: :range %>
  <%= f.input :explosives, as: :range %>
  <%= f.input :infiltration, as: :range %>
  <%= f.input :hacking, as: :range %>
  <%= f.input :lockpicking, as: :range %>
  <%= f.input :seduction, as: :range %>
  <%= f.button :submit, 'Add skillset', class: 'float-right' %>
<% end %>

app/views/pages/home.html.erb
<div class="hero-banner">
  <h1>The Mob Club</h1>
  <h2>click to enter</h2>
    <% if current_user.nil? %>
        <i id="logo" class="login-scroll fab fa-first-order"></i>
    <% else %>
      <%= link_to profile_path do %>
        <i id="logo" class="fab fa-first-order"></i>
       <% end %>
    <% end %>
    <i id="arrow-dwn" class="fas fa-angle-down"></i>
</div>




<div class="prp-value">
  <i class="fas fa-angle-up" id="page2TopArrow"></i>
  <div class="prp-container">
    <h1>1</h1>
    <h1>define <br> your skillset.</h1>
    <div class="prp-text">
      <p>Once you are in, you can let others know your worth. <br> From explosives expert to mastery in seduction - define your skills in your profile in an easy, convenient way.</p>
    </div>
  </div>
  <i class="fas fa-angle-down" id="page2BottomArrow"></i>
</div>

</div>
<div class="prp-value2">
  <i class="fas fa-angle-up" id="page3TopArrow"></i>
  <div class="prp-container2">
    <h1>2</h1>
    <h1>find the<br> perfect crime.</h1>
    <div class="prp-text2">
      <p>In our club, it’s easy to find the perfect match - all you have to do is browse through the latest, most evil plans ever conceived, and earning your coins is only a click away.</p>
    </div>
  </div>
  <i class="fas fa-angle-down" id="page3BottomArrow"></i>
</div>


</div>
<div class="prp-value3">
  <i class="fas fa-angle-up" id="page4TopArrow"></i>
  <div class="prp-container">
    <h1>3</h1>
    <h1>hire the best <br> mobsters.</h1>
    <div class="prp-text3">
      <p>Have a masterplan, that needs some expertise in opening bank vaults? Finding the right brains or muscle is now made easy - and discretion is the middle name of our Club.</p>
    </div>
  </div>
  <% unless user_signed_in? %>
    <i class="fas fa-angle-down" id="page4BottomArrow"></i>
  <% end %>
</div>

<% unless user_signed_in? %>
  <div id="login-page">
    <%# <i class="fas fa-angle-up" id="page5TopArrow"></i> %>

    <div class='devise-form-container text-center'>
      <h2>Welcome<br>to the<br>Mob Club</h2>

      <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class='devise-input-container'>
          <%= f.input :email,
                      label: false,
                      placeholder: 'Email',
                      required: false,
                      autofocus: false,
                      input_html: { autocomplete: "email", class: 'devise-input-field', class: 'color-light'} %>
          <%= f.input :password,
                      label: false,
                      placeholder: 'Password',
                      required: false,
                      input_html: { autocomplete: "current-password", class: 'devise-input-field', class: 'color-light mb-5 pb-5' } %>
        </div>

        <div>
          <div class='password-position'>
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
              <%= link_to "Forgot your password?", new_password_path(resource_name) %>
            <% end %>
          </div>
          <div class='devise-button-container'>
            <%= f.button :submit, "Log in", class:'devise-btn' %>
            <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
              <%= link_to "Create Account", new_registration_path(resource_name), class:'devise-btn-sign-up' %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
<% end %>

app/views/pages/profile.html.erb
<%# id="description-add-btn %>
<div class="container" id="profile-container" style="display:show">
  <div class="row">

    <div class="col-sm-12 col-md-4 col-lg-4">
      <div class="profile-info">
        <div class="user-info">
          <div class="avatar-container">
            <%= image_tag 'avatar-mob.jpg', class: 'profile-avatar' %>
          </div>
          <p id="username"><%= current_user.username %></p>
            <div>
              <% if current_user.description.blank? || current_user.description.nil? %>
                <a href="#" class="description-btn">Add description <i class="fas fa-pencil-alt"></i></a>
                <%= render 'edit_description' %>
              <% else %>
                <p><small><%= current_user.description %></small></p>
              <% end %>
            </div>
        </div>

        <div class="links-container">
          <% unless @user_has_skillset.nil? %>
            <p><a href="#" id="dashboard-btn" class="color-gold">Dashboard</p>
            <hr class="trans--grow hr0">
          <% end %>
          <p><%= link_to 'Edit profile', edit_user_registration_path, class: "color-gold" %></p>
          <hr class="trans--grow hr0">
          <p><%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "color-gold" %></p>
        </div>

      </div>
    </div>

    <div class="col-sm-12 col-md-8 col-lg-8">
      <% if current_user.skillset.nil? %>
        <div class="user-skillset-form" style="display:show">
          <%= render 'skillset-form' %>
        </div>
      <% else %>
        <div class="chart-container" style="display:show">
          <div class="chart">
            <canvas id="userChart"></canvas>
          </div>
          <div class="ranking">
            <p class="text-sm">Your ranking</p>
            <p><%= @ranking %></p>
            <p class="text-sm"><strong><%= @until_next_ranking %></strong>
              <%= @until_next_ranking == 1 ? 'point' : 'points' %>
              until <br><strong><%= @next_ranking %></strong></span></p>
          </div>
        </div>
      <% end %>

      <div id="dashboard-main" style="display:none">

        <div class="nav tabs">
          <a href="#jobs" class="tab active">Current crimes</a>
          <a href="#pending" class="tab">Pending requests</a>
          <a href="#event-manager" class="tab">Crime manager</a>
          <button class="create-event" id="create-event-btn">Organize Crime</button>
        </div>

        <div id="jobs" class="toggle" style="display:show">
          <div class="dashboard">
            <p><small>This is where you can keep track of all the crimes, felonies and misdeeds you have been applying for.</small></p>
            <% if @current_jobs.empty? %>
              <div class="empty-dash">
                <p class="op-9">You are currently not part of any Mob.</p>
                <p><%= link_to 'Search for Crimes', crimes_path, class: 'text-white-ruby' %></p>
              </div>
            <% else %>
            <ul>
              <% @current_jobs.each do |job| %>
                <li>
                  <%= link_to crime_path(job.crime) do %>
                    <h6><%= job.crime.title.upcase %></h6>
                  <% end %>
                  <div class="li-dash-org">
                  <p><small>
                      <% if (job.crime.date - Date.today).to_i == 0 %>
                        The crime is due <strong>today.</strong>
                      <% elsif (job.crime.date - Date.today).to_i < 0 %>
                        This crime has expired.
                      <% else %>
                        In <%= (job.crime.date - Date.today).to_i %> days.
                      <% end %>
                    </small></p>
                    <% unless job.crime.chatroom.nil? %>
                      <%= link_to crime_chatroom_path(job.crime, job.crime.chatroom) do %>
                        <span class="chat-profile-cta"><small>Go to chat</small></span>
                      <% end %>
                    <% end %>
                  </div>
                </li>
              <% end %>
            <% end %>
            </ul>
          </div>
        </div>

        <div id="pending" class="toggle" style="display:none">
          <div class="dashboard">
            <p><small>Waiting to get hired by these mobsters? Meanwhile, see how you can improve your general stats.</small></p>
            <% if @pending_requests.empty? %>
              <div class="empty-dash">
                <p class="op-9">You haven't applied for any crime yet.</p>
                <p><%= link_to 'Search for Crimes', crimes_path, class: 'text-white-ruby' %></p>
              </div>
            <% else %>
              <ul>
              <% @pending_requests.each do |job| %>
                <li>
                  <%= link_to crime_path(job.crime) do %>
                    <h6><%= job.crime.title.upcase %></h6>
                  <% end %>
                  <div class="li-dash-org">
                    <p><small>
                      <% if (job.crime.date - Date.today).to_i == 0 %>
                        The crime is due <strong>today.</strong>
                      <% elsif (job.crime.date - Date.today).to_i < 0 %>
                        This crime has expired.
                      <% else %>
                        In <%= (job.crime.date - Date.today).to_i %> days.
                      <% end %>
                    </small></p>
                  </div>
                </li>
              <% end %>
            <% end %>
            </ul>
          </div>
        </div>

        <div id="event-manager" class="toggle" style="display:none">
          <div class="dashboard">
            <p><small>Here you can keep track of all your most ingenous, inspired felonies. Access the details of your crimes and plan away!</small></p>
            <ul>
              <% @crimes.to_a.each do |crime| %>
                <li>
                  <%= link_to crime_path(crime.id) do %>
                    <h6><%= crime.title.upcase %></h6>
                  <% end %>
                  <div class="li-dash-org">
                    <% if crime.chatroom.nil? %>
                      <div>
                        <p class="float-left"><small>
                          <% if (crime.date - Date.today).to_i == 0 %>
                            This crime is due <strong>today.</strong>
                          <% elsif (crime.date - Date.today).to_i < 0 %>
                            This crime has expired.
                          <% else %>
                            In <%= (crime.date - Date.today).to_i %> days.
                          <% end %>
                        </small></p>
                      </div>
                      <div>
                        <small>
                        <%= simple_form_for [ crime, @chatroom ], class: 'chat-profile-cta' do |f| %>
                        <%= f.hidden_field :name %>
                        <%= f.button :submit, 'Go to chat', class: 'text-white-ruby  text-13' %>
                        <% end %>
                        </small>
                      </div>
                    <% else %>
                      <div>
                      <p><small>
                        <% if (crime.date - Date.today).to_i == 0 %>
                          This crime is due <strong>today.</strong>
                        <% elsif (crime.date - Date.today).to_i < 0 %>
                          This crime has expired.
                        <% else %>
                          In <%= (crime.date - Date.today).to_i %> days.
                        <% end %>
                      </small></p>
                      </div>
                      <div>
                      <%= link_to crime_chatroom_path(crime.id, crime.chatroom), class: ' text-13 text-white-ruby' do %>
                        <span class="chat-profile-cta"><small>Go to chat</small></span>
                      <% end %>
                      </div>
                    <% end %>
                  </div>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# Create event pop up %>

<div id="create-event-page" style="display:none">
  <%= render 'form' %>
</div>

<%# End of create event pop up %>

<script>
  if(window.location.href.substr(-2) !== "?r") {
    window.location = window.location.href + "?r";
  }
</script>