config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :crimes, except: :new do
    get 'crime_json' => 'crimes#crime_json'
    resources :chatrooms, except: [:index, :update, :edit] do
      resources :messages, only: :create
    end

    # crimes/:id/chatrooms/:id
    #for the chatroom, it needs: new, create, show, delete

    # crime_chatroom GET    /crimes/:crime_id/chatrooms/:id(.:format)       chatrooms#show
    # crime_teams POST   /crimes/:crime_id/teams(.:format) teams#create

    resources :teams, only: [:create, :update, :destroy]  #before it was resources :teams, only [:create, :index]
  end
  #added the line above to create a custom route for team index

  resources :skillsets, only: [:new, :create, :edit, :update]

  # resources :chatrooms, only: :show do
  #   resources :messages, only: :create
  # end

  get 'profile', to: 'pages#profile'
  get 'current_user_json' => 'pages#current_user_json'
end

app/models/crime.rb
class Crime < ApplicationRecord
  has_one :skillset, dependent: :destroy
  belongs_to :boss, class_name: 'User'
  belongs_to :right_hand, class_name: 'User', optional: true
  has_many :teams
  has_many :users, through: :teams
  has_one :chatroom, dependent: :destroy
  validates_associated :skillset

  validates :title, length: { minimum: 2 }, allow_blank: false
  validates :date, :location, presence: true
  validates :reward, numericality: true

  has_one_attached :photo
  include PgSearch::Model
  pg_search_scope :search_crime,
    against: [ :title, :description, :location ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  before_action :set_crime, except: [:index, :create, :crime_json]
  # before_action :permitted_skillset_attributes, only: [:show]

  def index

    if params[:query].present?
      @crimes = Crime.search_crime(params[:query])
    else
      @crimes = Crime.all
    end
  end

  def show
    @team = Team.new
    @current_teams = @crime.teams
  end

  def create
    @crime = Crime.new(crime_params)

    @crime.right_hand = User.find(right_hand_param[:right_hand]) unless right_hand_param[:right_hand].nil?

    @crime.boss = current_user

    unless @crime.save
      redirect_to profile_path, notice: 'There was an error. Please fill all the form fields.'
    end
  end

  def edit
    @skillset = Skillset.find(@crime.skillset.id)
  end

  def update
    # @crime.right_hand = User.find(right_hand_param[:right_hand]) unless right_hand_param[:right_hand].nil? || params[:crime].present?
    # if @crime.update(crime_params)
    #   redirect_to crime_path(@crime), notice: 'Plan updated!'
    # else
    #   render :new
    # end
    if params[:crime].present?
      @crime.right_hand = User.find(right_hand_param[:right_hand]) unless right_hand_param[:right_hand].nil?
      if @crime.update(crime_params)
        redirect_to crime_path(@crime), notice: 'Plan updated!'
      else
        render :new
      end
    else
      redirect_to crime_path(@crime), notice: "Don't click on upload for no reason."
    end
  end

  def destroy
    @crime.destroy
    # We may need to change this redirect path.
    redirect_to profile_path
  end

  def crime_json
    @crime = Crime.find(params[:crime_id])
    # @skillset = Skillset.where("crime_id = ?", params[:crime_id])
    render json: {
      close_combat: @crime.skillset.close_combat,
      long_range_weapons: @crime.skillset.long_range_weapons,
      mid_range_weapons: @crime.skillset.mid_range_weapons,
      explosives: @crime.skillset.explosives,
      infiltration: @crime.skillset.infiltration,
      hacking: @crime.skillset.hacking,
      lockpicking: @crime.skillset.lockpicking,
      seduction: @crime.skillset.seduction
    }
  end

  private

  def set_crime
    @crime = Crime.find(params[:id])
  end

  # def reward_lenght
  #   n_to_k = @crime.reward.to_s.length
  #   if n_to_k >= 5
  #     n_to_k[-1, -2, -3].gsub
  #   # new var  = count of digits
  #   # if new var >= 5
  #   # new var =
  #   # gsub last 3 digits to k;
  # end

  # def permitted_skillset_attributes
  #   @attributes = ['id', 'created_at', 'updated_at', 'user_id', 'crime_id']
  # end

  def crime_params
    params.require(:crime).permit(:title, :description, :date, :location, :reward, :photo)
  end

  def right_hand_param
    params.require(:crime).permit(:right_hand)
  end
end

app/views/crimes/_form.html.erb
<div class="crime-form-container">
  <div id="crime-form-1" style="display:show;">
    <%= simple_form_for @crime do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :location %>
      <a href="#" class="crime-form-btn">Next</a>
  </div>
  <div id="crime-form-2" style="display:none;">
      <%= f.input :date %>
      <%= f.input :reward %>
      <a href="#" class="crime-form-btn">Back</a>
      <%= f.button :submit, 'Next' %>
      <% end %>
  </div>
  <div id="crime-form-skillset" style="display:none;">
      <%= simple_form_for @skillset do |f| %>
      <%= f.input :close_combat, as: :range %>
      <%= f.input :long_range_weapons, as: :range %>
      <%= f.input :mid_range_weapons, as: :range %>
      <%= f.input :explosives, as: :range %>
      <%= f.input :infiltration, as: :range %>
      <%= f.input :hacking, as: :range %>
      <%= f.input :lockpicking, as: :range %>
      <%= f.input :seduction, as: :range %>
      <a href="#" class="skillset-form-btn">Back</a>
      <%= f.button :submit, 'Create Crime' %>
      <% end %>
  </div>
</div>

app/views/crimes/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/crimes/index.html.erb
<div class="mob-club-headers">
  <h1>Crimes that might interest you</h1>
  <p><%= Crime.count %> misdeeds available</p>
</div>


<!-- Responsive is done - any changes on theses classes, ask first please -->

<div class="crime-index-container">
  <div class="row">
    <div class="search-position">

      <%= form_tag crimes_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          id: "custom-search-bar",
          placeholder: "Find a crime"
        %>
        <%= submit_tag "Search", class: "btn btn-search" %>
      <% end %>

    </div>
  </div>

  <div class="row justify-content-center">

    <% @crimes.each do |crime| %>
      <% unless crime.boss == current_user || crime.right_hand == current_user %>
        <% how_many_days = crime.date - Date.today %>
        <div class="col-sm-offset-12 col-xl-offset-6">
          <%= link_to crime_path(crime) do  %>
          <% if how_many_days <= 0 %>
          <div class="crime-card-gone">
            <!-- remove this if statement if you wish to keep the cards all the same. -->
          <% else %>
          <div class="crime-card">
            <% end %>
            <div class="card-head">
              <h2><%= crime.title %></h2>
              <% if how_many_days < 30 && how_many_days > 0 %>
                <p><i class="fas fa-hourglass-end"></i> This misdeed must be executed soon.</p>
              <% end %>
              <% if how_many_days <= 0 %>
                <p><em>Time out - this crime has expired.</em></p>
              <% end %>

            <div class="card-details">
              <h3><i class="far fa-compass"></i> <%= crime.location %></h3>
              <% if how_many_days > 0 %>
                <h4>In <%= how_many_days.to_i %> days</h4>
              <% end %>
            </div>
            </div>
            <div class="card-reward">
              <p>reward</p>
              <h2><%= number_to_human crime.reward %>$</h2>
            </div>
          </div>
          <% end %>
          <!-- <li>Skillset?<%#= crime.skillset %></li> -->
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/crimes/show.html.erb
<div class="show-page-container">
  <div class="row">
    <div class="crime-new-cont col-sm-12 col-lg-6">
      <div class="crime-cont">
        <div class="reward-cont">
          <p>Reward<br></p>
          <h2><%= number_to_human @crime.reward %>$</h2>
        </div>
        <div class="crime-dtl">
          <div class="title-width">
          <h2><%= @crime.title %></h2>
          </div>
          <% unless @crime.right_hand.nil? %>
            <p><%= @crime.right_hand.username %></p>
          <% end %>
          <div class='day-location-container'>
            <% days_until = (@crime.date - Date.today).to_i %>
            <% if days_until == 0 %>
              <p>This event is today.</p>
            <% elsif days_until > 0 %>
              <p>In <%= days_until %> days</p>
            <% elsif days_until < 0 %>
              <p>Time out - this crime has expired.</p>
            <% end %>
            <p> <%= @crime.date %></p>
            <p><i class="far fa-compass"></i><%= @crime.location %></p>
          </div>
          <div class="descr-cont">
            <p><%= @crime.description %></p>
          </div>
          <hr class="trans--grow hr0">

          <div class='nav-btn-container'>
            <%= link_to crimes_path do %>
              <div class="actions-btn"> Back </div>
            <% end %>
            <% unless current_user == @crime.boss || current_user == @crime.right_hand %>
              <%= render "teams/new" %>
            <% end %>
            <% if current_user == @crime.boss || current_user == @crime.right_hand %>
              <%= link_to 'Update event', edit_crime_path(@crime), class: 'actions-btn' %>
            <% end %>
            <% if current_user == @crime.boss %>
              <%= link_to 'Cancel event', crime_path(@crime), method: :delete,
                  data: { confirm: 'Are you sure, mate?'}, class: 'actions-btn' %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tabs-cont">
        <% if current_user.id == @crime.boss_id || current_user.id == @crime.right_hand_id %>
        <div class="nav tabs">
          <a href="#active-members" class="tab active">Team members</a>
          <a href="#pending-members" class="tab">Pending members</a>
        </div>

        <div id="active-members" class="toggle" style="display:show">
          <h3>This is the list of accepted member of your mob.</h3>
            <% @current_teams.each do |current_team| %>
              <% if current_team.status == true %>
                <p><%= current_team.user.username %></p>

                <% if current_team.present? == false %>
                <p>There are no members in your squad yet.</p>
                <% end %>
              <% end %>
            <% end %> <!-- aqui por entao o container com a lista de membros activos-->
        </div>

        <div id="pending-members" class="toggle" style="display:none">
          <h3>These criminals are waiting for your confirmation:</h3>
            <% @current_teams.each do |current_team| %>
              <% if current_team.status == false %>
                <div class='team-list-members'>
                  <p><%= current_team.user.username %></p>
                  <div class='btn-status-container'>
                    <%= link_to crime_team_path(@crime, current_team), method: :patch do %>
                      <i class="far fa-check-square"></i>
                    <% end %>
                    <%= link_to crime_team_path(@crime, current_team), method: :delete,
                        data: { confirm: "Are you sure you want to decline #{current_team.user.username}?"} do %>
                      <i class="far fa-window-close"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %> <!-- aqui por entao o container com a lista de membros pending -->
        </div>
        <% else %>
          <% end %>

      </div>

    </div>

    <div class="crime-new-cont col-sm-12 col-lg-6">
        <div class="photo-cont">
        <!--   <div class='plan-photo'> -->
            <% if current_user.id == @crime.boss_id %>
            <% unless @crime.photo.attached? %>
              <%= simple_form_for @crime do |f| %>
              <%= f.input :photo, as: :file %>
              <%= f.submit 'Upload photo', class: "upload-style" %>
            <% end %>
          <% else %>
            <%= cl_image_tag @crime.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <% else %>
          <%= cl_image_tag @crime.photo.key, height: 300, width: 400, crop: :fill if @crime.photo.attached? %>
          <p style="font-weight:200">There are no added plans for this crime.</p>
          <% end %>
        <!-- </div> -->

        </div>
      <div class="arrow-cont">
        <div class="scrl-to-chart-arrow">
          <p>Scroll down see the stats this crime demands</p>
          <i id="chart-arrow-dwn" class="fas fa-angle-down"></i>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- CHART -->
<div class="cht-cont-1" id="the-chart">
  <% if current_user.id == @crime.boss_id %>
      <% if @crime.skillset.nil? %>
        <p> You need to add a skillset to your crime!</p>
      <% else %>
        <div class='chart'>
          <canvas id="myCrimeChart"></canvas>
        </div>
      <% end %>
      <% else %>
        <% if @crime.skillset.nil? %>
        <p style="margin-top:20px;"><small>The stats needed for this crime have not been defined yet.</small></p>
      <% else %>
        <div class='chart' id='crime-chart-container'>
          <canvas id="myCrimeChart"></canvas>
        </div>
      <% end %>
      <% end %>
    </div>
<!-- </div> -->
<%# This is used to pass the crime's id to the chart %>
<p id='paramsId' style="visibility: hidden;"><%= @crime.id %></p>



<!-- only bosses and right hands can see these two. Need to add logic for user -->
<!-- to see the current team only if current user id is part of the team -->
<%# if current_user.id == @crime.boss_id || current_user.id ==@crime.right_hand_id %>
<!-- only bosses and right hands can see these two. Need to add logic for user -->
<!-- to see the current team only if current user id is part of the team -->
<%#= link_to 'Enter team', crime_teams_path(@crime, @team), method: :post %>